/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        'washed-teal-50': '#f0fdfa',
        'washed-teal-100': '#ccfbf1',
        'washed-teal-200': '#99f6e4',
        'washed-teal-300': '#5eead4',
        'washed-teal-400': '#2dd4bf',
        'washed-teal-500': '#14b8a6',
        'washed-teal-600': '#0d9488',
        'washed-teal-700': '#0f766e',
        'washed-teal-800': '#115e59',
        'washed-teal-900': '#134e4a',
        'washed-cyan-50': '#ecfeff',
        'washed-cyan-100': '#cffafe',
        'washed-cyan-200': '#a5f3fc',
        'washed-cyan-300': '#67e8f9',
        'washed-cyan-400': '#22d3ee',
        'washed-cyan-500': '#06b6d4',
        'washed-cyan-600': '#0891b2',
        'washed-cyan-700': '#0e7490',
        'washed-cyan-800': '#155e75',
        'washed-cyan-900': '#164e63',
        'primary-teal-50': '#f0fdfa',
        'primary-teal-100': '#ccfbf1',
        'primary-teal-200': '#99f6e4',
        'primary-teal-300': '#5eead4',
        'primary-teal-400': '#2dd4bf',
        'primary-teal-500': '#14b8a6',
        'primary-teal-600': '#0d9488',
        'primary-teal-700': '#0f766e',
        'primary-teal-800': '#115e59',
        'primary-teal-900': '#134e4a',
        'primary-cyan-50': '#ecfeff',
        'primary-cyan-100': '#cffafe',
        'primary-cyan-200': '#a5f3fc',
        'primary-cyan-300': '#67e8f9',
        'primary-cyan-400': '#22d3ee',
        'primary-cyan-500': '#06b6d4',
        'primary-cyan-600': '#0891b2',
        'primary-cyan-700': '#0e7490',
        'primary-cyan-800': '#155e75',
        'primary-cyan-900': '#164e63',
        'Neutrals/neutrals-1': '#ffffff',
        'Neutrals/neutrals-2': '#fcfcfd',
        'Neutrals/neutrals-3': '#f5f5f6',
        'Neutrals/neutrals-4': '#f0f0f1',
        'Neutrals/neutrals-5': '#d9d9dc',
        'Neutrals/neutrals-6': '#c0bfc4',
        'Neutrals/neutrals-7': '#8d8c95',
        'Neutrals/neutrals-8': '#5b5966',
        'Neutrals/neutrals-9': '#464553',
        'Neutrals/neutrals-10': '#282637',
        'Neutrals/neutrals-11': '#201f30',
        'Neutrals/neutrals-12': '#161427',
        'Neutrals/neutrals-13': '#020014',
        'brand-washedTeal': '#2dd4bf',
        'brand-washedCyan': '#22d3ee',
        'brand-primaryTeal': '#14b8a6',
        'brand-primaryCyan': '#06b6d4',
        'brand-dark': '#001a1f',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
